# Generated by Django 4.2.1 on 2023-05-21 16:23

from django.db import migrations
from property.models import Owner, Flat


def migrate_owner_data(apps, schema_editor):
    flats = Flat.objects.all()

    for flat in flats:
        # New экземпляр модели Owner
        owner, created = Owner.objects.get_or_create(
            full_name=flat.owner,
            phone=flat.owners_phonenumber,
            normalized_phone=flat.owner_pure_phone
        )
        # Привязать созданного владельца к квартире
        flat.owners.add(owner)
        flat.save()


def revert_owner_data(apps, schema_editor):
    Owner.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_alter_flat_has_balcony_alter_flat_id_alter_like_id_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_owner_data, revert_owner_data),
    ]
